name: HomesThatWork
main: com.dsnyder.homesthatwork.WorkingHomes
version: 2.1.0
author: Dan Snyder
description: A simple home plugin that actually works
commands:
  homesthatwork:
    description: Main plugin command. See /htw help for command list.
    usage: /homesthatwork [version|help] [command]
    aliases: [htw]